---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgBeg7OEEeJMy/jEZINTEj9MYj7Ob/Bu98Tt4vLmvqzPFwe6vRdcWJ1ysGpcm5IXFepd1Wc8DormksuVjgKMXfWi2UFr0b6wxDdeFlbwdFRscppR76DtnMVLaFLDVS2TySDhHibqe1x6vxtc3TuD9qxb+Y+5kau+etNeaRGslATR04DEZ9F6QfKaaLM7QDaYWUg5OK3SKvgkXSCV32oEmMU/Esd2boAqvneRAvanDNOgacpEACfNAfqp3RUYo+SXhFur6lPKiYskcV2EbAVNhxIOM4caU/GppGRf3mepR3p9sgQxS7MUnrDvqiRCn5XqYiwldoLDVBLAStf/2fY6mQ7LFolVMsrHTLC8YG5cX12+l8tSRJpJKuHaow72VRqqK0PtoKBZFYgQmZBocFYiAFs1tiEut7d/RGQ3sYKjnDFY6jRBpTYFMKWdVA1qQm4eMatdTNuTnmlakwqZivkoEhjz+O33VyY6FN8Uq2iXBw4zIbfJSRFBJE4ATxpP/Bin0RU0itIy1K/9RaMaaAokL8zIUiNKnPubfg5JwKBhVuAOhthmA1JOb3nEotp0r8q7RwJ5KfimarrGDfAYS8v8+9sZch9iD2Is3uxJUenM/tKMWy/m1A9l5lqF+RT8P8zRuF8zrpa+GkBo9wUFicERXRH+cd6ODo2CWBDkc9CAayJlWARdGk3/TCCQOiBPA9TEAm5efRIh5pJSQw==
    DB_USER: AgAwu+6nrvqronaqZErxAA9ZbxPWWwqaORrte2/oXQZ4gerEuF61CCJzaEtIEYOl1M4oBbFpFuYxwpWn6I8LA13cjaPeS/Na0J8w5usJyFtx/XQpg9TBSgEx3+8QeaPrkWWPf/mIOjoM8vzNpk36KDKWTZ0kPtd1bfrhm5ai+LZdK8gFJIBelSnIpGgJrGxkh1KVOaySyPCNQu4DO81yUz4gyRSOMMg8WtKYRmdc6ljcfqVygdky9r9x5SQf2gx77z0zk0Pmv7YFu8d2jsnN7utzi0mMcQRVwH+hCYhTyEAQNCu//jtpfAIIVCAEi2Gf4xZ6/L8sgypBLG106eCCSZOloH1GmHRfZ/p4mg1isA5auz/jU7fTtPVSb+GTWW34IZNKtQjMnR+VmAH/VCkdhXDfjxhZn/tEcWfLPb27DYDLfDCvupt7Ldr+ci+WlEMt+dOxuNUfhB2ooTeU4eriTqzSJN+1g3Azfm6GLtEosLzqTityjGG1xZWPfhdF6vYdNa+J6heDSWHhLngTf4/G5R8xQ6papXCZqL9a8JMR6O/QqcnUqKa0Ox0pKt7Vu6tf4RbEkHZGQhngJHMX+mPB5XYg0nVI4sqtr/QEOQZmneDAbz/EBU81adIQlk03Zv2MEMr0MFpnV660Xlmn7vxnLXrt6/A74G88g5PB1IsSmETCyPlCUiCtAD7B7zDFykgxuYoWuMjkuirikg==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-prod
    type: Opaque
