apiVersion: v1
kind: Secret
metadata:
  name: itxa-db2-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "210"
type: Opaque
stringData:
  databaseName: B2BIDB
  dbUser: db2inst1
  dbPassword: db2inst1
  dbHostIp: "db2-lb"
  #dbHostIp: "172.21.227.68"
  dbPort: "50000"
  accessKey: "ea60793f18fa4c72bf74802aeab2c68d"
  secretKey: "9cdcee52718471ed8c42b345f1fa8d8623d7c6232fa95255"
  # dbCurrentSchema: "DB2INST1"
